### ISSUE TITLE
Consider parsing schema.rb instead of annotate

### ISSUE THREAD

**Issue by iftheshoefritz** [iftheshoefritz/solargraph-rails#10]
If solargraph_rails parses the schema, there won't be a dependency on annotate. Pros and cons:

Pro:
- universal to Rails
- simpler parsing (no need to distinguish between annotate comments and other comments in the model)

Con:
- go-to-definition will have to choose between going to the schema (where they can't edit stuff) or going to the model file (where they can't see the definition of the attribute)
- Some apps don't have a schema.rb. I only know of one IRL, so I assume they are rare.

**Comment by iftheshoefritz** [comment]
@julianrubisch pointed out that some Rails apps that want to use advanced DB features will use `structure.sql`.

Annotate is a very common gem and I haven't yet seen any reason _not_ to use it.

It's possible that in future there could be different strategies to parse `db/schema`, `structure.sql`, `annotate` and/or others.

**Comment by garymh** [comment]
I'd love this! I really like the `annotate` gem, but I work on a large project that I can't easily add gems to...

**Comment by julianrubisch** [comment]
I think it would be nice to have configurable options, 👍🏻

**Comment by iftheshoefritz** [comment]
This is on my to-do list, I'd love to see this gem become relevant outside of just annotate users. It's behind association support and increased stability for now though. Happily accepting pull requests though :).

**Comment by grncdr** [comment]
Just want to add that I'd also prefer a solution driven by the Rails schema. I've never used annotate and I have to deal with some _very_ wide models, so something that duplicates all the attributes as comments in the source is a non-starter.

> I started down that route and couldn't identify a small enough subset of Rails to load for startup times to be reasonable.

I took a look at this, but `require 'active_record'` alone takes over a second on my (not slow) machine. Loading my app is even slower, so I decided to explore a different approach. If you look at `db/schema.rb`, it uses an extremely small subset of [ActiveRecord::ConnectionAdapters::SchemaStatements](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html), so I wrote a hacky little script that provides that API and requires `db/schema.rb`. Check [the gist](https://gist.github.com/grncdr/a34c344ac1c8622dab7278660b80f3b4) to see what I mean.

With that, we get all the tables & columns (-> model attributes) in about 100ms. I know this doesn't cover `schema.sql` users, but for that you need a real database connection (which I'd avoid if possible) or a SQL parser (which would make sense, but is a big jump in complexity). 

> One thing to think about: where does go-to-definition take you if you're divining attributes from ActiveRecord?

The most sensible thing IMO is `db/schema.rb`. If you were parsing SQL you could presumably provide locations there as well, but I have no idea how the Solargraph server feels about non-ruby files.

**Comment by grncdr** [comment]
Just a comment about associations: ActiveRecord requires these to be declared in the source anyways, so using a standard source-analyzing plugin makes more sense there IMO.

**Comment by jhirn** [comment]
> A comment about associations: ActiveRecord requires these to be declared in the source anyways, so using a standard source-analyzing plugin makes more sense there IMO.

This is a great point. In fact if I get code completion from the schema or annotations, it may autocomplete a method where there is no `has_many` or `belongs_to` due to this, you'd be completing methods that in fact, don't exist. I'm actually curious if you can evaluate the model. Even scanning the model attributes won't capture inherited traits correctly in all cases. 

It feels like `Model.reflect_on_all_associations(:has_many)` etc.. might be a really good option, but I'm not sure if it's an option to dynamically add metadata to. I feel bad complaining at all because I have literally no time to assist with this gem.

**Comment by grncdr** [comment]
> I'm actually curious if you can evaluate the model.

Depending on what you mean by "evaluate" here, I'd argue it's a bad idea. Anything that relies on booting the Rails app is a non-starter IMO, it's just too slow.

> Even scanning the model attributes won't capture inherited traits correctly in all cases.

Could you elaborate on this with an example? I didn't really understand what you mean so I can't guess if it's a fundamental limitation of using `schema.rb` or not.

--

I should clarify that my gist above is a proof-of-concept hack and possibly a useless one. More appropriate would be leveraging the fact that Solargraph is _already_ parsing schema.rb anyways and recognizing the method calls inside `Schema.define` blocks to build up the same schema information my script does.

The missing piece is mapping model class names to tables. For that you would need to perform appropriate inflections, recognize `ActiveRecord::Base.table_name=`
and (trickier) handle `SomeNamespace.table_prefix`.

I'm personally unlikely to pursue all of that directly for Solargraph. I'm much more interested in https://github.com/castwide/solargraph/issues/265 since I find writing a YARD extension is relatively simple and would give more value (e.g. improve autocomplete and YARD docs together).

**Comment by iftheshoefritz** [comment]
Fantastic conversation, thanks folks. My effort on this gem is focused on fixing an sg bug that breaks association inference, but this is probably next up.

**Comment by iftheshoefritz** [comment]
One more thought, I'd probably add schema or annotate parsing as configurable options. Anyone have ideas about how the developer UX of configuration should work?

Solargraph already has a yaml file, I think I'd prefer to configure things in there rather than creating another yaml file.

**Comment by grncdr** [comment]
A solargraph-rails key in solargraph config seems fine to me.

**Comment by jhirn** [comment]
> Could you elaborate on this with an example? I didn't really understand what you mean so I can't guess if it's a fundamental limitation of using `schema.rb` or not.

The case I was thinking about was a concern or mixin where an association can't be gleamed from a simple filescan. But maybe there's a way to look for `include` in the file. I'm not really sure. No LSP experience, just a happy customer here!

**Comment by asok** [comment]
@iftheshoefritz would you consider merging a PR that would fallback to reading the schema file if the annotations are missing?

**Comment by asok** [comment]
@iftheshoefritz I pushed a WIP commit to my branch https://github.com/asok/solargraph-rails/commit/1d4a45e462189d315f5e0b989dc14154f881a3a3

It's not yet tested and the test suite is not updated. I wanted to know whether something like could be merged in.

**Comment by grncdr** [comment]
Not sure if it's bad form to mention a different project, but https://github.com/alisnic/solargraph-arc seems to parse schemas pretty well already.

**Comment by asok** [comment]
> https://github.com/alisnic/solargraph-arc seems to parse schemas pretty well already.

Indeed it works pretty well. And tbh the codebase seems more mature. @iftheshoefritz I think it makes sense to add a "alternatives" section in the readme file and mention this project.

**Comment by jhirn** [comment]
I didn't have great luck with solargraph-arc. It seems to destroy ActiveSuport method completion (my test is always `"".in?`) and the AR completions also didn't seem to work in my preliminary trial. It's a pretty big effort to support this and not to ding the maintainer, but there hasn't been any releases for almost 6 weeks (12/20).

**Comment by asok** [comment]
> I would definitely like to get some schema parsing going, get your PR in and let's have a look :
I think there's no point in reinventing the wheel since solargraph-arc achieved that already. Plus you mention that you collaborate with the author of solargraph-arc so maybe the projects will merge together.

**Comment by iftheshoefritz** [comment]
This feature will be coming with #28.
